### PR TITLE
Generate rating model attributes and controller

### PR DESCRIPTION
**Pull request by itsjoyce**

### CODE REVIEW

**Comment by jamescavallo** [comment]
lgtm

**Review by jamescavallo — APPROVED** [review]

**Comment by jamescavallo** [comment]
Maybe add validations to model tho?

**Comment by itsjoyce** [comment]
> Maybe add validations to model tho?
Good idea! I added validations and solved merge conflicts.

**Review by jpaints3 — APPROVED** [review]
looks good to me

**Pull request merged**
